# Aula 09 #

### 9.1: Matrizes e Vetores Multidimensionais ###

#### 9.1.1: Definição ####

Matrizes e vetores multidimensionais são generalizações dos vetores vistos anteriormente. Através delas é possível associar dois ou mais tipos de dados em uma mesma variável. Podemos, por exemplo, criar uma matriz que associa os alunos e suas respectivas notas.

In [ ]:
#EXEMPLO 9.1: Declarando e imprimindo uma matriz através de listas

mat = [[] for i in range(3) ] #dentro de uma lista vazia cria-se 3listas vazias internas
print(mat)


In [ ]:
#EXEMPLO 9.2: Criar uma matriz 3x4 onde cada posição (i, j) contém o valor i*j

mat=[]

for i in range(3):
    l=[]
    for j in range(4):
        l.append(i*j)
    mat.append(l)
print(mat)

In [ ]:
#EXEMPLO 9.3: Fazer o mesmo do exemplo 9.2 utilizando a forma do exemplo 9.1

mat=[[i*j for j in range(4)] for i in range(3)]
print(mat)

#### 9.1.2: Acessando os dados de uma matriz ####

Para acessar um dado da matriz, digitamos da seguinte maneira:

< nome_da_matriz >[< indíce_linha >][< indíce_coluna >]

In [ ]:
#EXEMPLO 9.4: acessando um dado de uma matriz e o alterando

mat=[[0 for i in range(7)]for i in range(8)] #cria uma matriz nula 6x7
print('mat = ', mat)

mat[5][6]=1
print('matAlterada = ', mat)

In [ ]:
#EXEMPLO 9.5: trabalhando com dados de uma matriz

mat=[[i*j for j in range(4)]for i in range(4)]
print('mat = ', mat)
print('mat[2][3] = ', mat[2][3])
mat[2][3]=0
print('matAlt = ', mat)
print('mat[2][3]Alt = ', mat[2][3])

#### 9.1.3: Declarando Vetores Multidimentsionais ####

Podemos criar matrizes com dimensões d1xd2xd3x...xdn. Para isso escrevemos

[[...[[]for i(n-1) in range(d(n-1))]...] for i(2) in range(d(2)]for i(1) in range(d(1))]

In [ ]:
#EXEMPLO 9.6: Matriz 3x4x5 com zeros

mat=[[[0 for k in range(5)] for j in range(4) ] for i in range(3)]
print(mat)

In [1]:
#EXEMPLO 9.7: Fazer um programa que leia uma matriz nxn e imprima

n=int(input("Dim(M1): "))
mat=[[]for i in range(n)] #cria uma matriz n linhas com vetores vazios
print('Digite os valores dos elementos da matriz')

#Leitura dos dados da matriz
for i in range(n):
    for j in range(n):
        aux=float(input('Mat[{}][{}]='.format(i+1, j+1)))
        mat[i].append(aux)

#Impressão da matriz linha por linha
for i in range(n):
    for j in range(n):
        print(mat[i][j], end=' ')
    print()
    
print(len(mat))


Dim(M1): 2
Digite os valores dos elementos da matriz
Mat[1][1]=1
Mat[1][2]=2
Mat[2][1]=3
Mat[2][2]=4
1.0 2.0 
3.0 4.0 
2


In [10]:
#EXEMPLO 9.8: Soma de duas Matrizes

#Leitura da dimensão das matrizes quadradas
n=int(input("Dim(Mi): "))

#Criação das matrizes
mat1=[[]for i in range(n)] #cria uma matriz n linhas com vetores vazios
mat2=[[]for i in range(n)]
mat3=[[0 for j in range(n)]for i in range(n)] #Matriz inicialmente nula
print('Digite os valores dos elementos da matriz1')

print()
print('Matriz 1')
#Leitura dos dados da matriz 1
for i in range(n):
    for j in range(n):
        aux=float(input('Mat1[{}][{}]='.format(i+1, j+1)))
        mat1[i].append(aux)

print()
print('Matriz 2')
#Leitura dos dados da matriz 2
for i in range(n):
    for j in range(n):
        aux=float(input('Mat2[{}][{}]='.format(i+1, j+1)))
        mat2[i].append(aux)

#calculando a soma das matrizes
for i in range(n):
    for j in range(n):
        mat3[i][j]=mat1[i][j]+mat2[i][j]

print()
print('Matriz 3')
#Impressão da matriz linha por linha
for i in range(n):
    for j in range(n):
        print(mat3[i][j], end=' ')
    print()

Dim(Mi): 2
Digite os valores dos elementos da matriz1

Matriz 1
Mat1[1][1]=1
Mat1[1][2]=2
Mat1[2][1]=3
Mat1[2][2]=4

Matriz 2
Mat2[1][1]=1
Mat2[1][2]=2
Mat2[2][1]=3
Mat2[2][2]=4

Matriz 3
2.0 4.0 
6.0 8.0 


In [11]:
#EXEMPLO 9.9: Multiplicação de duas matrizes

#Leitura da dimensão das matrizes quadradas
n=int(input("Dim(Mi): "))

#Criação das matrizes
mat1=[[]for i in range(n)] #cria uma matriz n linhas com vetores vazios
mat2=[[]for i in range(n)]
mat3=[[0 for j in range(n)]for i in range(n)] #Matriz inicialmente nula
print('Digite os valores dos elementos da matriz1')

print()
print('Matriz 1')
#Leitura dos dados da matriz 1
for i in range(n):
    for j in range(n):
        aux=float(input('Mat1[{}][{}]='.format(i+1, j+1)))
        mat1[i].append(aux)

print()
print('Matriz 2')
#Leitura dos dados da matriz 2
for i in range(n):
    for j in range(n):
        aux=float(input('Mat2[{}][{}]='.format(i+1, j+1)))
        mat2[i].append(aux)


#Calculando o produto das duas matrizes
for i in range(n):
    for j in range(n):
        for k in range(n):
            mat3[i][j]=mat3[i][j] + (mat1[i][k]*mat2[k][j])

print()
print('Matriz 3')
#Impressão da matriz linha por linha
for i in range(n):
    for j in range(n):
        print(mat3[i][j], end=' ')
    print()

Dim(Mi): 2
Digite os valores dos elementos da matriz1

Matriz 1
Mat1[1][1]=1
Mat1[1][2]=1
Mat1[2][1]=1
Mat1[2][2]=1

Matriz 2
Mat2[1][1]=1
Mat2[1][2]=1
Mat2[2][1]=1
Mat2[2][2]=1

Matriz 3
2.0 2.0 
2.0 2.0 


In [14]:
#EXEMPLO 9.10: Transposta de uma matriz

#Leitura da dimensão das matrizes quadradas
n=int(input("Dim(Mi): "))

#Criação das matrizes
mat1=[[]for i in range(n)] 
matT=[[0 for j in range(n)]for i in range(n)]
print()
print('Matriz 1')

#Leitura dos dados da matriz 1
for i in range(n):
    for j in range(n):
        aux=float(input('Mat1[{}][{}]='.format(i+1, j+1)))
        mat1[i].append(aux)

#Matriz transposta        
for i in range(n):
    for j in range(n):
        matT[i][j]=mat1[j][i]

print()
print('Matriz 1')
#Impressão da matriz linha por linha
for i in range(n):
    for j in range(n):
        print(mat1[i][j], end=' ')
    print()
        
print()
print('Matriz Tranposta')
#Impressão da matriz linha por linha
for i in range(n):
    for j in range(n):
        print(matT[i][j], end=' ')
    print()

Dim(Mi): 2

Matriz 1
Mat1[1][1]=1
Mat1[1][2]=2
Mat1[2][1]=3
Mat1[2][2]=4

Matriz 1
1.0 2.0 
3.0 4.0 

Matriz Tranposta
1.0 3.0 
2.0 4.0 


### 9.2: NumPy ###

NumPy é uma biblioteca muito útil para aplicações científicas, já que ela possuí uma série de funções que facilitam o tratamento de vetores, matrizes, operações de algebra linear, dentre outras coisas.

Para instalar essa biblioteca acessamos: http://www.numpy.org/

O objeto mais simples da biblioteca é o array, que serve para criar vetores homogêneos multi-dimensionais.

In [2]:
#EXEMPLO 9.11: Criando um array de 1D a partir de uma lista

import numpy as np #importa a biblioteca numpy e usa 'np' como nome para chamar

a=np.array([1, 2, 3])
print('a=', a)
print('dim(a)=', a.ndim)
print('tam(a)=', a.size)

a= [1 2 3]
dim(a)= 1
tam(a)= 3


In [5]:
#EXEMPLO 9.12: Criando um array a com dim(a)>1 a partir de listas
a=np.array([[1, 2, 3], [4, 5, 6]])
print('a=', a)
print('dim(a)=', a.ndim)
print('tam(a)=', a.size)

a= [[1 2 3]
 [4 5 6]]
dim(a)= 2
tam(a)= 6


In [8]:
#EXEMPLO 9.13: Utilizando outras funções para criar arrays

a=np.arange(10) #cria um array de dim(a)=1 e tam(a)=10
print('a=np.arrange(10):\n',a)
a=a.reshape(2,5) #rearranja o array a em um 2x5
print('a.reshape(2,5):\n',a)

a=np.arrange(10):
 [0 1 2 3 4 5 6 7 8 9]
a.reshape(2,5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
#EXEMPLO 9.14: Criando um array contendo apenas zeros ou uns

a=np.zeros(3)
print('a=np.zeros(3):\n',a)

a=np.zeros((3,4))
print('a=np.zeros((3,4)):\n',a)

a=np.ones((2,5))
print('a=np.ones((2,5)):\n',a)

a=np.zeros(3):
 [0. 0. 0.]
a=np.zeros((3,4)):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a=np.ones((2,5)):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
#EXEMPLO 9.15: Operadores em arrays

a=np.ones((2,3))
print('a=np.ones((2,3)):\n', a)
print()
a=a+1 #soma 1 a cada elemento de a
print('a=a+1:\n',a)
print()
a=4*a #multplica por 4 todos os elemetnos de a
print('a=4*a:\n',a)
print()
a=a**3 #eleva ao cubo todos os elementos de a
print('a**3:\n',a)

a=np.ones((2,3)):
 [[1. 1. 1.]
 [1. 1. 1.]]

a=a+1:
 [[2. 2. 2.]
 [2. 2. 2.]]

a=4*a:
 [[8. 8. 8.]
 [8. 8. 8.]]

a**3:
 [[512. 512. 512.]
 [512. 512. 512.]]


In [18]:
#EXEMPLO 9.16: Multiplicação de matrizes

a=np.arange(9).reshape(3,3)
b=([[2,2,2], [2,2,2], [2,2,2]])

print('a:\n',a)
print('b:\n',b)

print('axb:\n',np.dot(a,b)) #dot(a,b) calcula AXB
print('bxa:\n',np.dot(b,a))

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b:
 [[2, 2, 2], [2, 2, 2], [2, 2, 2]]
axb:
 [[ 6  6  6]
 [24 24 24]
 [42 42 42]]
bxa:
 [[18 24 30]
 [18 24 30]
 [18 24 30]]


In [22]:
#EXEMPLO 9.17: Matriz inversa
import numpy.linalg as npl  #o pacote numpy.linalg possui diversas funções de algeLin


a=np.array([[1, 2, 3], [0, 1, 4], [0, 0, 1]])
print('a:\n', a)
print()
a=npl.inv(a) #calcula a inversa de a
print('inv(a):\n', a)


a:
 [[1 2 3]
 [0 1 4]
 [0 0 1]]

inv(a):
 [[ 1. -2.  5.]
 [ 0.  1. -4.]
 [ 0.  0.  1.]]
